NumPy - Numerical Python
Advantages of Numpy arrays:
1. Allows several Mathematical Operations
2. Faster Operations


In [1]:
import numpy as np



In [2]:
#list vs Numpy  - Time Taken

In [3]:
from time import process_time

Time taken by a list

In [4]:
python_list = [i for i in range(100000)]

start_time = process_time()
python_list = [i + 5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.00999912799999958


In [6]:
np_array = np.array([i for i in range(100000)])

start_time = process_time()
np_array = np.array([i +5 for i in np_array])
end_time = process_time()
print(end_time - start_time)

0.0202345510000006


In [7]:
np_array = np.array([i for i in range(100000)])

start_time = process_time()
#np_array = np.array([i +5 for i in np_array])
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.0012812679999996135


In [8]:
list1 = [1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [9]:
np_array = np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

nd => n- dimension array


In [10]:
#creating a 1-d array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
a.shape

(4,)

In [13]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


(2, 3)

In [14]:
b.shape

(2, 3)

In [16]:
c= np.array([1,2,3], dtype = float)
print(c)

[1. 2. 3.]


Initial placeholder in numpy arrays

In [18]:
#creating a numpy array of zeros
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
#create a numpy array of ones
y = np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
#array of a specific value
z = np.full((3,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [24]:
#creating an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
#create a numpy array with random values
b= np.random.random((4,5))
print(b)

[[0.97848056 0.1146531  0.44404099 0.53360413 0.00324775]
 [0.56929772 0.79822806 0.86762865 0.67835078 0.64140269]
 [0.03209025 0.30849604 0.67065924 0.06625731 0.46378455]
 [0.74306984 0.63732941 0.86563947 0.31976243 0.08787736]]


In [28]:
#random integer value within a specific range
c= np.random.randint(15,200,(3,4))
print(c)

[[149 155  87 111]
 [186 150  48  38]
 [152  32  42 164]]


In [33]:
#array of evenly spaced value --> specifying total number of values required
d = np.linspace(50,100,5)
print(d)

[ 50.   62.5  75.   87.5 100. ]


In [36]:
#array of evenly spaced values -> specifying the step
e = np.arange(10,60,7)
print(e)

[10 17 24 31 38 45 52 59]


In [37]:
#convert a list to a numpy array/ can do with tuple too
list2 = [1,2,3,4,5]
np_array =np.asarray(list2)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Analysing a numpy array

In [38]:
c = np.random.randint(10,90,(5,5))
print(c)

[[61 55 61 73 25]
 [28 21 16 70 85]
 [64 35 22 89 42]
 [31 25 86 26 31]
 [84 58 35 25 55]]


In [39]:
print(c.shape)
#c.shape

(5, 5)


In [41]:
#number of dimension
c.ndim
#print(c.ndim)

2

In [43]:
#numbr of elements in array
c.size

25

In [44]:
#checking the data type of values in the array
c.dtype

dtype('int64')

Mathematical operations on a np array


In [46]:
list1 = [1,2,3,4]
list2 = [5,6,7,8,9]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [49]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)# shape should be same to perform this operation

[[2 8 6]
 [9 7 3]
 [6 4 8]]
[[15 16 16]
 [18 10 11]
 [12 17 18]]
[[17 24 22]
 [27 17 14]
 [18 21 26]]


In [50]:
print(a-b)
print(a*b)
print(a/b)

[[-13  -8 -10]
 [ -9  -3  -8]
 [ -6 -13 -10]]
[[ 30 128  96]
 [162  70  33]
 [ 72  68 144]]
[[0.13333333 0.5        0.375     ]
 [0.5        0.7        0.27272727]
 [0.5        0.23529412 0.44444444]]


In [52]:
a = np.random.randint(0,10,(4,4))
b = np.random.randint(10,20,(4,4))
print(a)
print(b)

[[0 7 1 6]
 [3 7 7 0]
 [2 4 1 7]
 [3 8 2 0]]
[[15 16 16 17]
 [19 13 11 15]
 [15 18 10 14]
 [15 18 11 13]]


In [53]:
#another way of operation
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 23 17 23]
 [22 20 18 15]
 [17 22 11 21]
 [18 26 13 13]]
[[-15  -9 -15 -11]
 [-16  -6  -4 -15]
 [-13 -14  -9  -7]
 [-12 -10  -9 -13]]
[[  0 112  16 102]
 [ 57  91  77   0]
 [ 30  72  10  98]
 [ 45 144  22   0]]
[[0.         0.4375     0.0625     0.35294118]
 [0.15789474 0.53846154 0.63636364 0.        ]
 [0.13333333 0.22222222 0.1        0.5       ]
 [0.2        0.44444444 0.18181818 0.        ]]


Array Manipulation


In [54]:
rray = np.random.randint(0,10,(2,3))
print(rray)
print(rray.shape)

[[4 6 2]
 [8 6 5]]
(2, 3)


In [55]:
#transpose the matrix
trans = np.transpose(rray)
print(trans)
trans.dtype

[[4 8]
 [6 6]
 [2 5]]


dtype('int64')

In [56]:
rray = np.random.randint(0,10,(2,3))
print(rray)
print(rray.shape)

[[4 0 9]
 [0 1 2]]
(2, 3)


In [57]:
trans2 = rray.T
print(trans2)
trans2.dtype

[[4 0]
 [0 1]
 [9 2]]


dtype('int64')

In [58]:
#reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
a.shape

[[1 5 6]
 [5 7 4]]


(2, 3)

In [59]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[1 5]
 [6 5]
 [7 4]]
(3, 2)
