Creating a Matrix using numpy library

In [1]:
import numpy as np

In [2]:
matrix_1 = np.array([[1,2],[3,4]])
print(matrix_1)

[[1 2]
 [3 4]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
matrix_2.shape

(3, 3)

Creating Matrices with Random values

In [6]:
random_matrix =np.random.rand(4,4)
print(random_matrix)

[[0.3671379  0.97696768 0.83359185 0.28010785]
 [0.38926034 0.02837718 0.55372254 0.63052685]
 [0.21165619 0.25800071 0.63500001 0.67328841]
 [0.11222828 0.18380049 0.37679237 0.78006227]]


In [7]:
#creating matrix with random integers
random_int_matrix = np.random.randint(100, size = (4,5))
print(random_int_matrix)

[[87 50 74 50  0]
 [24 45 74 40 84]
 [96  5 72 78 26]
 [93 87 51 79 54]]


Matrix with all the values as 1


In [9]:
matrix_3 = np.ones((3,4))
print(matrix_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
matrix_4  = np.ones((2,3), dtype =int)
print(matrix_4)

[[1 1 1]
 [1 1 1]]


NULL matrix or zero matrix

In [12]:
null_matrix = np.zeros((3,3))
print(null_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Identity matrix

In [13]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# identity_matrix = np.eye((3,3), dtype = int)
# print(identity_matrix)

TypeError: ignored

Transpose of a matrix

In [15]:
#matrix with random integer values
a = np.random.randint(200, size =(4,5))
print(a)

[[ 50 193  93 138  19]
 [160  17 165 138 106]
 [117 149 115 149 106]
 [102 165 114  34 136]]


In [17]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[ 50 160 117 102]
 [193  17 149 165]
 [ 93 165 115 114]
 [138 138 149  34]
 [ 19 106 106 136]]


Matrix Addition

Two Matrices can be added only if they have the same shape

In [18]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [19]:
print(A)
print(B)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [20]:
A.shape
B.shape

(2, 2)

In [21]:
sum = A+B
print(sum)

[[ 8 10]
 [12 14]]


In [22]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [23]:
print(matrix_1)
print(matrix_2)

[[1 1 4]
 [0 8 8]
 [8 7 2]]
[[11  4  0]
 [11 18  2]
 [ 3  2  3]]


In [25]:
sum = np.add(matrix_1, matrix_2)
print(sum)

[[12  5  4]
 [11 26 10]
 [11  9  5]]


In [26]:
#Matrix Subtraction
A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

print(A)
print(B)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [27]:
diff = A - B
print(diff)

[[-4 -4]
 [-4 -4]]


In [29]:
difference = np.subtract(A,B)
print(difference)

[[-4 -4]
 [-4 -4]]


In [30]:
#Multiplying a matrix by a scalar
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[1 6 3 9]
 [4 6 0 4]
 [9 6 6 1]
 [2 1 9 2]]


In [32]:
product = np.multiply(x,y)

print(product)

[[ 5 30 15 45]
 [20 30  0 20]
 [45 30 30  5]
 [10  5 45 10]]


In [33]:
#Multiplying 2 Matrices
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))


In [35]:
product = np.dot(matrix_3, matrix_4)
print(product)

[[19  8 12 10]
 [29 10 18 14]
 [25 10 10  6]]


In [36]:
product.shape

(3, 4)

Element wise Matrix Multiplication

In [37]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))
product = np.multiply(matrix_3, matrix_4)
print(product)

[[6 6 0]
 [0 3 0]
 [8 0 8]]
